# Global settings
title: MSE Club
email: mse@mse.skule.ca
senpai: Henry Lu
project: https://github.com/nanosmasher/mse.skule.ca

address:
    - WB39 Wallberg building
    - 200 College Street
    - Toronto Ontario, Canada
    - M56 3E5

social:
    facebook: #
    twitter: #
    instagram: #

# Build settings
markdown: kramdown
permalink: '/:categories/:short_year:month:day/'
relative_permalinks: false
#include: [.htaccess]
excerpt_separator: "<!-- more -->"

# Text
keywords: ['Materials','Science','Engineering','Club','MSE','MSEClub','UofT','Academic','Anti-Calendar','Guide','Courses','Buckyball']
description: 'The Materials Science and Engineering Club (MSE Club) at the University of Toronto represents the interests of over 200 MSE undergraduate students in the Faculty of Applied Science and Engineering. The club excecutives organize events like barbeques, smokers, tournaments, movie nights, sports, and the annual MSE dinner dance. They provide services such as locker rentals, common room cleanups, and anouncement boards for the community.'

color:
    primary: 'blue'
    accent: 'purple'